"""Removendo a tabela teste

Revision ID: b28cdbd637fb
Revises: 
Create Date: 2025-03-11 11:40:37.869285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28cdbd637fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teste', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
