"""alteração na coluna

Revision ID: e5052920c900
Revises: b28cdbd637fb
Create Date: 2025-03-12 17:26:17.764423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5052920c900'
down_revision = 'b28cdbd637fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('id_user_revisao',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('id_user_revisao',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
