name: Deploy Docusaurus Site

on:
  push:
    branches:
      - feat/Alteracoes-Necessarias-para-deploy-da-documentacao-Docusaurus

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v2

      # 2. Setup Node.js (versão 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependências (no diretório docs)
      - name: Install dependencies
        working-directory: docs
        run: npm install

      # 4. Build do site Docusaurus
      - name: Build Docusaurus site
        working-directory: docs
        run: npm run build

      - name: Deploy Docusaurus site
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: "ian.simao@sou.inteli.edu.br"
          GIT_USER: x-access-token
        run: npx docusaurus deploy --remote-url "https://x-access-token:${GITHUB_TOKEN}@github.com/Inteli-College/2025-1A-T12-EC05-G03.git"
