name: Deploy to GitHub Pages
on:
  push:
    branches:
      - develop 

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/front-end  # Garante que o GitHub Pages receba o site do diretório correto

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
