name: Deploy Front-End to GitHub Pages
on:
  push:
    branches:
      - gh-pages-front-end  # Dispara quando houver push na branch gh-pages-front-end

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Mudar para a branch gh-pages-front-end
        run: |
          git checkout gh-pages-front-end  # Muda para a branch já existente
          git rm -rf .  # Remove os arquivos antigos
          cp -r src/front-end/* .  # Copia os novos arquivos para a branch
          git add .
          git commit -m "Deploy Front-End"
          git push origin gh-pages-front-end  # Atualiza a branch no GitHub

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
